cleanup unrelated classes when rooting (GSI-720)
ghga-de/schemapack pull request #34
Opened 2024-04-25 12:32 UTC by KerstenBreuer

```
... from schemapack.
```

2024-05-10 09:52 UTC, sbilge requested changes
Thanks. Only a minor comment for a typo fix.

2024-05-10 09:52 UTC, sbilge commented on examples/schemapack/valid/unrelated_classes_rooted.schemapack.yaml
> +            # is kept.
```suggestion
description: Two unrelated classes # but rooted to one class so that only that class is
            # kept.
```

2024-05-14 14:51 UTC, lkuchenb approved these changes
@KerstenBreuer I've not done a review myself but @sbilge's concern was addressed, so I've run the template update and conflict resolution.

2024-05-15 08:59 UTC, KerstenBreuer commented
Great, thank you

2024-05-15 09:39 UTC, sbilge approved these changes

2024-05-15 14:09 UTC, merged